apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      name: backend-app-deployment
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-app
          image: ssamantr/kube-helloworld:1.0.0
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels: 
    app: backend-app
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: backend-app
  ports: 
    - name: http
      port: 8080 # ClusterIp Service Port
      targetPort: 8080 # Container Port