apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-nginx-app-deployment
  labels:
    app: frontend-nginx-app
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-nginx-app
  template:
    metadata:
      labels:
        app: frontend-nginx-app
        tier: frontend
    spec:
      containers:
        - name: frontend-nginx-app
          image: ssamantr/kube-frontend-nginx:1.0.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels: 
    app: frontend-nginx-app
    tier: frontend     
spec:
  type: NodePort 
  selector:
    app: frontend-nginx-app
  ports: 
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31234