apiVersion: v1
kind: Service
metadata:
  name: deployment-node-port-service
spec:
  type: NodePort 
  selector: 
    app: backend-app
  ports: 
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 31233
    