apiVersion: v1
kind: Service
metadata:
  name: user-management-clb-service
  labels:
    app: user-management-restapp
spec:
  type: LoadBalancer # Default - Classic Load Balancer
  selector:
    app: user-management-restapp
  ports:
    - port: 8090
      targetPort: 8090