apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dev
  name: ebs-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 4Gi