apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.6
          env:
            - name: MYSQL_DATABASE
              value: 'user-management'
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-db-creds
                  key: db-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-db-creds
                  key: db-password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-db-creds
                  key: db-password
          ports:
            - name: mysql-port
              containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
            - name: user-management-db-creation-script
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: ebs-mysql-pvc
        - name: user-management-db-creation-script
          configMap:
            name: user-management-db-creation-script
