apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: mysql
spec:
  clusterIP: None # This means we are going to use Pod IP. This signifies a headless service.
  selector:
    app: mysql
  ports:
    - port: 3306