apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: user-management-service
  labels:
    app: user-management-restapp
spec:
  type: NodePort
  selector:
    app: user-management-restapp
  ports:
    - port: 8090
      targetPort: 8090
#      nodePort: 31231 # required for namespace demo in order to avoid port conflict across different namespaces