apiVersion: v1
kind: Secret
metadata:
  namespace: dev
  name: mysql-db-creds
type: Opaque
# type: Opaque. From k8s point of view the contents of this Secret is unstructured, which can contain arbitrary key-value pairs.
data:
  db-user: 'dXNlcg==' # echo -n 'user' | base64
  db-password: 'cGFzc3dvcmQ=' # echo -n 'password' | base64