kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: local-cluster
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30001 # Required for NodePort Demo
        hostPort: 30001
        protocol: TCP
  - role: worker
  - role: worker