apiVersion: v1
kind: Service
metadata:
  name: user-management-service
  labels:
    app: user-management-restapp
spec:
  type: NodePort
  selector:
    app: user-management-restapp
  ports:
    - port: 8090
      targetPort: 8090
      nodePort: 31231