apiVersion: v1
kind: Service
metadata:
  name: backend-app-nodeport-service # Name of the Service
spec:
  type: NodePort 
  selector:
    app: backend-app  # Loadbalance traffic across Pods matching this label selector
  ports: 
    - name: http
      port: 8080 # Service Port: Accept traffic sent to port 80
      targetPort: 8080 # Container Port
      nodePort: 31231 # NodePort