apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: backend-app-rs
spec:
  replicas: 3 # 3 Pods should exist at all times.
  selector:   # Pods label should be defined in ReplicaSet label selector
    matchLabels:
      app: backend-app
  template: 
    metadata:
      name: backend-app-rs
      labels:
        app: backend-app # Atleast 1 Pod label should match with ReplicaSet Label Selector
    spec:
      containers:
        - name: backend-app
          image: ssamantr/kube-helloworld:1.0.0
          ports:
            - containerPort: 8080